WORLDBANK

https://www.imf.org/en/publications/weo/weo-database/2025/april

IMF/FMI — World Economic Outlook Database (WEO), April 2025 Edition.

In [1]:
import requests
import pandas as pd

In [2]:
url = "https://api.worldbank.org/v2/topic?format=json&per_page=100"

response = requests.get(url)
response.raise_for_status()

dados = response.json()

temas = pd.DataFrame(dados[1])

temas

,id,value,sourceNote
0,1,Agriculture & Rural Development,For the 70 percent of the world's poor who liv...
1,2,Aid Effectiveness,Aid effectiveness is the impact that aid has i...
2,3,Economy & Growth,Economic growth is central to economic develop...
3,4,Education,Education is one of the most powerful instrume...
4,5,Energy & Mining,The world economy needs ever-increasing amount...
5,6,Environment,Natural and man-made environmental resources –...
6,7,Financial Sector,An economy's financial markets are critical to...
7,8,Health,Improving health is central to the Millennium ...
8,9,Infrastructure,Infrastructure helps determine the success of ...
9,10,Social Protection & Labor,The supply of labor available in an economy in...
10,11,Poverty,For countries with an active poverty monitorin...
11,12,Private Sector,"Private markets drive economic growth, tapping..."
12,13,Public Sector,Effective governments improve people's standar...
13,14,Science & Technology,"Technological innovation, often fueled by gove..."
14,15,Social Development,"Data here cover child labor, gender issues, re..."
15,16,Urban Development,Cities can be tremendously efficient. It is ea...
16,17,Gender,Gender equality is a core development objectiv...
17,18,Millenium development goals,
18,19,Climate Change,Climate change is expected to hit developing c...
19,20,External Debt,Debt statistics provide a detailed picture of ...
20,21,Trade,Trade is a key means to fight poverty and achi...

In [3]:
# IDs DAS APIs POR TEMA

topic_id = 12  # exemplo: Economy & Growth

url = f"https://api.worldbank.org/v2/indicator?topic={topic_id}&format=json&per_page=20000"

response = requests.get(url)
response.raise_for_status()

indicadores = pd.DataFrame(response.json()[1])

indicadores[["id", "name", "sourceNote"]].head(20)

#indicadores.to_excel('Economy & Growth.xlsx', index= False)

indicadores

,id,name,unit,source,sourceNote,sourceOrganization,topics
0,1.0.HCount.1.90usd,Poverty Headcount ($1.90 a day),,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
1,1.0.HCount.2.5usd,Poverty Headcount ($2.50 a day),,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
2,1.0.HCount.Mid10to50,Middle Class ($10-50 a day) Headcount,,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
3,1.0.HCount.Ofcl,Official Moderate Poverty Rate-National,,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of data from Nation...,"[{'id': '11', 'value': 'Poverty '}]"
4,1.0.HCount.Poor4uds,Poverty Headcount ($4 a day),,"{'id': '37', 'value': 'LAC Equity Lab'}",The poverty headcount index measures the propo...,LAC Equity Lab tabulations of SEDLAC (CEDLAS a...,"[{'id': '11', 'value': 'Poverty '}]"
...,...,...,...,...,...,...,...
19995,per_sa_sf.adq_q2_preT_tot,Adequacy of benefits in 2nd quintile (%) - Sch...,,"{'id': '29', 'value': 'The Atlas of Social Pro...",Total transfer amount received by all benefici...,ASPIRE,"[{'id': '10', 'value': 'Social Protection & La..."
19996,per_sa_sf.adq_q2_rur,Adequacy of benefits in 2nd quintile (%) - Sch...,,"{'id': '29', 'value': 'The Atlas of Social Pro...",Total transfer amount received by all benefici...,ASPIRE,"[{'id': '10', 'value': 'Social Protection & La..."
19997,per_sa_sf.adq_q2_tot,Adequacy of benefits in 2nd quintile (%) - Sch...,,"{'id': '29', 'value': 'The Atlas of Social Pro...",Total transfer amount received by all benefici...,ASPIRE,"[{'id': '10', 'value': 'Social Protection & La..."
19998,per_sa_sf.adq_q2_urb,Adequacy of benefits in 2nd quintile (%) - Sch...,,"{'id': '29', 'value': 'The Atlas of Social Pro...",Total transfer amount received by all benefici...,ASPIRE,"[{'id': '10', 'value': 'Social Protection & La..."
19999,per_sa_sf.adq_q3_preT_tot,Adequacy of benefits in 3rd quintile (%) - Sch...,,"{'id': '29', 'value': 'The Atlas of Social Pro...",Total transfer amount received by all benefici...,ASPIRE,"[{'id': '10', 'value': 'Social Protection & La..."

In [4]:
from zipfile import ZipFile
from io import BytesIO

import requests
import matplotlib.pyplot as plt
from config import DB_CONFIG
from sqlalchemy.types import Integer, Float, String, Date
from sqlalchemy import create_engine, URL

EXTRACT (EXTRAIR)

Exemplo desemprego

In [5]:
# Indicador Banco Mundial / ILO:
# SL.UEM.TOTL.ZS = Unemployment, total (% of total labor force) (modeled ILO estimate)

indicador = 'SL.UEM.TOTL.ZS'

url = f"https://api.worldbank.org/v2/en/indicator/{indicador}?downloadformat=csv"

response = requests.get(url)
response.raise_for_status()


zip_file = ZipFile(BytesIO(response.content))

arquivo_dados = [
    nome for nome in zip_file.namelist()
    if nome.startswith(f"API_{indicador}") and nome.endswith(".csv")
][0]

df = pd.read_csv(
    zip_file.open(arquivo_dados),
    skiprows=4
)

df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.214915,7.244843,7.459106,7.974302,8.407412,7.869470,7.676548,7.571697,7.539233,NaN
2,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.184000,11.192000,11.187000,11.710000,12.006000,14.100000,14.008000,13.687000,13.351000,NaN
3,Africa Western and Central,AFW,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.284646,4.336100,4.393903,4.799306,4.670761,3.596538,3.203355,3.174915,3.192973,NaN
4,Angola,AGO,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.617000,16.602000,16.497000,16.696000,15.799000,14.124000,14.051000,14.020000,14.108000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,"Yemen, Rep.",YEM,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.611000,17.593000,17.213000,17.963000,18.312000,17.224000,16.944000,16.970000,17.322000,NaN
262,South Africa,ZAF,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,27.035000,26.906000,28.468000,29.217000,34.007000,33.268000,32.098000,32.279000,32.391000,NaN
263,Zambia,ZMB,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.529000,5.032000,5.538000,6.032000,5.197000,5.993000,5.861000,5.898000,5.918000,NaN
264,Zimbabwe,ZWE,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,6.350000,6.788000,7.373000,8.617000,9.540000,10.087000,9.348000,9.435000,9.293000,NaN

TRANSFORM (Transformar)

In [7]:
# FILTRANDO PELAS AS 15 MAIORES ECONOMIA

paises = {
    "United States": "Estados Unidos",
    "China": "China",
    "Germany": "Alemanha",
    "Japan": "Japão",
    "India": "Índia",
    "United Kingdom": "Reino Unido",
    "France": "França",
    "Italy": "Itália",
    "Brazil": "Brasil",
    "Canada": "Canadá",
    "Russian Federation": "Rússia",
    "Mexico": "México",
    "Korea, Rep.": "Coreia do Sul",
    "Australia": "Austrália",
    "Spain": "Espanha"
}

df_15 = df.copy()

df_15 = df_15[df_15["Country Name"].isin(paises.keys())].copy()

df_15["pais"] = df_15["Country Name"].map(paises)

In [10]:
df_15

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70,pais
13,Australia,AUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.345,5.143,6.394,5.022,3.728,3.668,3.942,4.090,NaN,Austrália
29,Brazil,BRA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,12.329,11.936,13.697,13.158,9.231,7.947,6.801,5.970,NaN,Brasil
35,Canada,CAN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,5.837,5.690,9.657,7.527,5.279,5.415,6.351,6.907,NaN,Canadá
40,China,CHN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.310,4.560,5.000,4.550,4.980,4.670,4.590,4.615,NaN,China
55,Germany,DEU,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.384,3.163,3.881,3.594,3.137,3.071,3.400,3.711,NaN,Alemanha
70,Spain,ESP,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,15.255,14.104,15.532,14.914,13.033,12.179,11.400,10.376,NaN,Espanha
76,France,FRA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,9.018,8.415,8.009,7.871,7.303,7.335,7.400,7.542,NaN,França
80,United Kingdom,GBR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.145,3.657,4.472,4.864,3.768,4.025,4.361,4.746,NaN,Reino Unido
108,India,IND,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.652,6.510,7.859,6.380,4.822,4.172,4.173,4.219,NaN,Índia
115,Italy,ITA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,10.538,9.884,9.192,9.497,8.069,7.627,6.500,6.391,NaN,Itália
118,Japan,JPN,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.467,2.351,2.809,2.808,2.614,2.600,2.500,2.451,NaN,Japão
125,"Korea, Rep.",KOR,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.824,3.746,3.931,3.639,2.857,2.675,2.784,2.683,NaN,Coreia do Sul
153,Mexico,MEX,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.275,3.477,4.440,4.019,3.256,2.765,2.678,2.673,NaN,México
201,Russian Federation,RUS,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,4.871,4.513,5.620,4.749,3.867,3.076,2.430,2.133,NaN,Rússia
250,United States,USA,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.896,3.669,8.055,5.349,3.650,3.638,4.022,4.198,NaN,Estados Unidos

In [11]:
anos = [str(ano) for ano in range(1991, 2026)]

df_desem = df_15.melt( 
    id_vars=["pais", "Country Code"], 
    value_vars=anos, 
    var_name="ano", 
    value_name="desemprego" 
)

df_desem["ano"] = df_desem["ano"].astype(int)

df_desem["desemprego"] = pd.to_numeric(df_desem["desemprego"], errors="coerce")

df_desem = df_desem.dropna(subset=["desemprego"])

df_desem = df_desem.sort_values(["ano", "desemprego"], ascending=[True, False])

print(df_desem.info())

df_desem

<class 'pandas.core.frame.DataFrame'>
Index: 525 entries, 5 to 523
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   pais          525 non-null    object
 1   Country Code  525 non-null    object
 2   ano           525 non-null    int64
 3   desemprego    525 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 20.5+ KB
None

              pais Country Code   ano  desemprego
5          Espanha          ESP  1991      15.929
2           Canadá          CAN  1991      10.316
9           Itália          ITA  1991      10.097
0        Austrália          AUS  1991       9.586
6           França          FRA  1991       9.134
..             ...          ...   ...         ...
514       Alemanha          DEU  2025       3.711
521  Coreia do Sul          KOR  2025       2.683
522         México          MEX  2025       2.673
520          Japão          JPN  2025       2.451
523         Rússia          RUS  2025       2.133

[525 rows x 4 columns]

In [ ]:
# #SALVANDO EM CSV

# df_desem.to_csv(
#     "desemprego_15_maiores_economias_1991_2025.csv",
#     sep=";",
#     index=False,
#     decimal=",",
#     encoding="utf-8-sig"
# )

LOAD (Carregar)

In [12]:
#conectar como banco aula04

url_conexao = URL.create(
    drivername="postgresql+psycopg2",
    username=DB_CONFIG["user"],
    password=DB_CONFIG["password"],
    host=DB_CONFIG["host"],
    port=DB_CONFIG["port"],
    database="aula04" # alterando para aula04    
)

engine = create_engine(url_conexao)

print("Conexão com o aula04")

Conexão com o aula04

In [13]:
df_desem.to_sql(
    name="desemprego_15",
    con=engine,
    if_exists="replace", #"append"
    index=False,
    dtype={
        "pais": String(),
        "Country Code": String(),
        "ano": Integer(),
        "desemprego": Float()
    }
)

print('Tabela criada/carregada com sucesso!')

# fecha/libera as conexões do SQLAlchemy
engine.dispose()

Tabela criada/carregada com sucesso!